# Workflow to check whether changes to master fulfill all requirements.
name: Status checks

on:
  push:
    branches: [ master ]
  pull_request:
  # Make it possible to trigger the checks manually.
  workflow_dispatch:

jobs:
    build-frontend:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: react-cra
        run: npm install

      - name: Build project
        working-directory: react-cra
        run: npm run build

    golangci:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: stable
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v7
          with:
            working-directory: server
            version: v2.0

    test-go:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Build Docker image for testing
          run: docker build -t iban-issuer-tests --file Dockerfile.test .

        - name: Run tests
          run: docker run iban-issuer-tests
 